# -*- coding: utf-8 -*-
"""MiguelApablaza_004_A

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ujhpkEitegn9ueDxaV5SWjnLYYnIx-pp
"""

import datetime

entradas_platinum = [None] * 21
entradas_gold = [None] * 30
entradas_silver = [None] * 50
asistentes = []
ganancias_totales = 0


def mostrar_menu():
    print("----- Menú -----")
    print("1. Comprar entradas")
    print("2. Mostrar ubicaciones disponibles")
    print("3. Ver listado de asistentes")
    print("4. Mostrar ganancias totales")
    print("5. Salir")
    opcion = input("Ingrese una opción: ")
    return opcion


def solicitar_cantidad_entradas():
    while True:
        cantidad = int(input("Ingrese la cantidad de entradas a comprar (1-3): "))
        if cantidad >= 1 and cantidad <= 3:
            return cantidad
        else:
            print("Cantidad inválida. Intente nuevamente.")


def mostrar_ubicaciones_disponibles():
    print("----- Ubicaciones Disponibles -----")
    print("Platinum:")
    for i, entrada in enumerate(entradas_platinum[1:], start=1):
        if entrada is None:
            print(f"Asiento {i}")
        else:
            print(f"Asiento {i} - Vendida")
    print("Gold:")
    for i, entrada in enumerate(entradas_gold[1:], start=21):
        if entrada is None:
            print(f"Asiento {i}")
        else:
            print(f"Asiento {i} - Vendida")
    print("Silver:")
    for i, entrada in enumerate(entradas_silver[1:], start=51):
        if entrada is None:
            print(f"Asiento {i}")
        else:
            print(f"Asiento {i} - Vendida")


def comprar_entradas():
    cantidad = solicitar_cantidad_entradas()
    tipo_entrada = None
    precio_entrada = 0
    rango_asientos = ()

    if cantidad == 1:
        tipo_entrada = "Platinum"
        precio_entrada = 120000
        rango_asientos = (1, 21)
    elif cantidad == 2:
        tipo_entrada = "Gold"
        precio_entrada = 80000
        rango_asientos = (21, 51)
    elif cantidad == 3:
        tipo_entrada = "Silver"
        precio_entrada = 50000
        rango_asientos = (51, 101)

    mostrar_ubicaciones_disponibles()

    for i in range(cantidad):
        while True:
            asiento = int(input(f"Ingrese el número del asiento {i+1}: "))
            if asiento >= rango_asientos[0] and asiento < rango_asientos[1]:
                if tipo_entrada == "Platinum":
                    if entradas_platinum[asiento] is None:
                        entradas_platinum[asiento] = asiento
                        break
                    else:
                        print("El asiento seleccionado no está disponible.")
                elif tipo_entrada == "Gold":
                    if entradas_gold[asiento] is None:
                        entradas_gold[asiento] = asiento
                        break
                    else:
                        print("El asiento seleccionado no está disponible.")
                elif tipo_entrada == "Silver":
                    if entradas_silver[asiento] is None:
                        entradas_silver[asiento] = asiento
                        break
                    else:
                        print("El asiento seleccionado no está disponible.")
            else:
                print("Número de asiento inválido. Intente nuevamente.")

    run = input("Ingrese el RUN del asistente (sin puntos ni guion): ")
    asistentes.append(run)

    global ganancias_totales
    ganancias_totales += precio_entrada * cantidad

    print("La operación se ha realizado correctamente.")


def mostrar_listado_asistentes():
    print("----- Listado de Asistentes -----")
    asistentes_ordenados = sorted(asistentes)
    for asistente in asistentes_ordenados:
        print(asistente)


def mostrar_ganancias_totales():
    print("----- Ganancias Totales -----")
    print(f"Ganancias totales: ${ganancias_totales}")


def obtener_fecha_actual():
    fecha_actual = datetime.datetime.now()
    return fecha_actual.strftime("%d/%m/%Y")


def main():
    while True:
        opcion = mostrar_menu()

        if opcion == "1":
            comprar_entradas()
        elif opcion == "2":
            mostrar_ubicaciones_disponibles()
        elif opcion == "3":
            mostrar_listado_asistentes()
        elif opcion == "4":
            mostrar_ganancias_totales()
        elif opcion == "5":
            fecha_actual = obtener_fecha_actual()
            print("Saliendo del sistema...")
            print("Gracias por usar la aplicación de Creativos.cl")
            print("Fecha: " + fecha_actual)
            break
        else:
            print("Opción inválida. Intente nuevamente.")


main()